### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by xmrbk** [Kelvin-1013/solana-trading-bot-js#1]
when i run it it says RPC error and it stops the program itself, the bot transferred all my SOL to the other wallet, resulting in me losing all sol 

https://solscan.io/tx/3o6HDsUGLCCJ71nQE7iG1rpGC4E98VGEHEHcjo4bRdAeEKdfuKwzFNBeRTEcefNrvXsEDNgyzbkk3jrNsUMWoNkT

**Comment by Gordonhills** [comment]
Hello @xmrbk 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[solanascan Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Kelvin-1013** [comment]
![image](https://github.com/user-attachments/assets/8f560b36-7a20-4329-83eb-254961eff721)

**Comment by Kelvin-1013** [comment]
![image](https://github.com/user-attachments/assets/b1a46912-4cad-4b97-b136-521fa44c4fe5)

What did you enter here?

**Comment by Kelvin-1013** [comment]
The reason why you lose money  is because you didn't fully understand this project so mistyped parameter
