### ISSUE TITLE
SCAM PRJ

### ISSUE THREAD

**Issue by xmrbk** [Kelvin-1013/solana-trading-bot-js#2]
https://solscan.io/tx/5MYNSjUGd1aJJbnQ36q2gvPb2rJp5TC85AfU6PT8dJvqfmFH9D1xhUAuJjiv68TdxPrcSCw5Dz2kDihdnwukP6Mq

IT TRANSFERED SOL FROM MY WALLET TO DEjqvqDFnDrBB3XhACLd8pXrVtBYXVrbcUebVRmnHGgZ

**Comment by Kelvin-1013** [comment]
![image](https://github.com/user-attachments/assets/e0136d65-c93f-4b71-b0f6-d2e3649cff0d)

**Comment by Kelvin-1013** [comment]
![image](https://github.com/user-attachments/assets/73285540-e248-4da5-8f16-7e3e6c6abfe3)
